version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5100:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3100:3000"
    volumes:
      - ./frontend:/app

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3101:3000"
